from tartaruga import *

'''
exibir()
pra_frente(100)
esquerda(90)
pra_frente(100)
esquerda(90)
pra_frente(100)
esquerda(90)
pra_frente(100)
terminar()
'''

exibir()
velocidade(1)
andar_ate(100, 120)
cor_caneta("azul")
andar_horizontal(50)
cor_caneta("amarelo")
andar_vertical(50)
cor_caneta("verde")
carimbar()
print(direcao())
direita(180)
escrever("texto")
esquerda(45)
print(posicao())
pra_frente(100)
cor_caneta("vermelho")
esquerda(45)
pra_tras(50)
cor_caneta("preto")
voltar_casa()
ponto()
cor_caneta("rosa")
levantar_caneta()
pra_frente(100)
abaixar_caneta()
pra_tras(100)
mudar_direcao(270)
cor_preenchimento("amarelo")
iniciar_preenchimento()
for i in range(4):
    pra_frente(60)
    esquerda(90)
parar_preenchimento()
terminar()
#reiniciar()
